spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:~/data/ncode-project
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test